import "../styles/globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Loader from "./Loader";

export const metadata = {
  title: `Jimmy's portfolio`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className="bg-main h-screen px-5 md:px-11 lg:">

        <Header bgColor='bg-main' textColor='text-black' />
        {children}
        <Footer bgColor='bg-transparent' textColor='text-black' />
        
      </body>
    </html>
  );
}
