import '../styles/globals.css'
import Header from "./Header";
import Footer from "./Footer";

export const metadata = {
  title: `Jimmy's portfolio`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='overflow-hidden'>
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
